# Generated by Django 6.0.8 on 2026-08-09 12:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('offer_img', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('search_bg', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('testmonial_bg', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('header_footer_color', models.CharField(blank=True, max_length=150)),
                ('text_color', models.CharField(blank=True, max_length=150)),
                ('button_color', models.CharField(blank=True, max_length=150)),
                ('googletagmanager', models.CharField(blank=True, max_length=150)),
                ('google_map', models.CharField(blank=True, max_length=1000)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('working_days', models.CharField(blank=True, help_text='Example: Mon - Sat', max_length=100)),
                ('working_hours', models.CharField(blank=True, help_text='Example: 10:00 AM - 6:00 PM', max_length=100)),
                ('smtpserver', models.CharField(blank=True, max_length=50)),
                ('smtpemail', models.CharField(blank=True, max_length=50)),
                ('smtppassword', models.CharField(blank=True, max_length=100)),
                ('smtpport', models.CharField(blank=True, max_length=5)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('footer_text', models.CharField(blank=True, max_length=250, null=True)),
                ('copy_right', models.CharField(blank=True, max_length=100)),
                ('privacy_policy', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('terms_conditions', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('disclaimer', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('cookies', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
            ],
            options={
                'verbose_name_plural': '0. Website Settings',
            },
        ),
    ]
