# Generated by Django 6.0.8 on 2026-08-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='search_bg',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='testmonial_bg',
        ),
    ]
