# Generated by Django 6.0.8 on 2026-08-10 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_setting_search_bg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading of the slider', max_length=200)),
                ('highlighted_text', models.CharField(blank=True, help_text='Text which will appear highlighted', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('badge_text', models.CharField(blank=True, max_length=100)),
                ('badge_color', models.CharField(choices=[('sky', 'Sky'), ('blue', 'Blue'), ('cyan', 'Cyan'), ('orange', 'Orange'), ('green', 'Green'), ('purple', 'Purple')], default='sky', max_length=20)),
                ('image', models.ImageField(upload_to='hero-sliders/')),
                ('background', models.CharField(default='from-sky-50 to-white', help_text='Tailwind gradient classes', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSliderButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Button text', max_length=100)),
                ('url', models.CharField(help_text='Example: https://example.com, tel:+919999999999, mailto:info@example.com, #appointment', max_length=500)),
                ('style', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class, e.g. fa-solid fa-calendar-check', max_length=100)),
                ('open_new_tab', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='home.heroslider')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
