# Generated by Django 6.0.8 on 2026-08-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_heroslider_herosliderbutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='ABOUT CLOUD EYES', max_length=100)),
                ('badge_icon', models.CharField(blank=True, default='fa-solid fa-eye', max_length=100)),
                ('title', models.CharField(default='Better Vision Begins', max_length=200)),
                ('highlighted_title', models.CharField(default='With Better Care.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='about/')),
                ('image_alt', models.CharField(blank=True, default='About Cloud Eyes', max_length=200)),
                ('counter_number', models.CharField(default='15+', max_length=50)),
                ('counter_text', models.CharField(default='Years of Trusted Eye Care', max_length=150)),
                ('feature_1_icon', models.CharField(default='fa-solid fa-eye', max_length=100)),
                ('feature_1_title', models.CharField(default='Eye Examination', max_length=100)),
                ('feature_1_description', models.CharField(default='Accurate Diagnosis', max_length=200)),
                ('feature_2_icon', models.CharField(default='fa-solid fa-user-doctor', max_length=100)),
                ('feature_2_title', models.CharField(default='Expert Doctors', max_length=100)),
                ('feature_2_description', models.CharField(default='Experienced Specialists', max_length=200)),
                ('feature_3_icon', models.CharField(default='fa-solid fa-microscope', max_length=100)),
                ('feature_3_title', models.CharField(default='Modern Equipment', max_length=100)),
                ('feature_3_description', models.CharField(default='Latest Technology', max_length=200)),
                ('feature_4_icon', models.CharField(default='fa-solid fa-heart', max_length=100)),
                ('feature_4_title', models.CharField(default='Patient Care', max_length=100)),
                ('feature_4_description', models.CharField(default='Friendly Environment', max_length=200)),
                ('button_1_text', models.CharField(default='Read More', max_length=100)),
                ('button_1_url', models.CharField(default='#about', max_length=500)),
                ('button_1_icon', models.CharField(blank=True, max_length=100)),
                ('button_2_text', models.CharField(default='Contact Us', max_length=100)),
                ('button_2_url', models.CharField(default='tel:+919999999999', max_length=500)),
                ('button_2_icon', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
    ]
