# Generated by Django 6.0.8 on 2026-08-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='badge_text',
            field=models.CharField(default='ABOUT', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='button_2_url',
            field=models.CharField(default='tel:+', max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_alt',
            field=models.CharField(blank=True, default='About', max_length=200),
        ),
    ]
