# Generated by Django 6.0.8 on 2026-08-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_aboutsection_badge_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
    ]
