# Generated by Django 6.0.8 on 2026-08-10 07:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle or tagline', max_length=300, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('read_legacy', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Main image for About section', null=True, upload_to='about/')),
                ('about_title', models.CharField(blank=True, max_length=200, null=True)),
                ('about_subtitle', models.CharField(blank=True, help_text='Subtitle or tagline', max_length=300, null=True)),
                ('about_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mission_title', models.CharField(blank=True, max_length=200, null=True)),
                ('mission_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('vision_title', models.CharField(blank=True, max_length=200, null=True)),
                ('vision_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hero_title', models.CharField(blank=True, help_text='Main Hero Heading', max_length=250, null=True)),
                ('hero_highlight', models.CharField(blank=True, help_text='Highlighted text in Hero Title', max_length=150, null=True)),
                ('hero_subtitle', models.CharField(blank=True, help_text='Small heading above Hero Title', max_length=200, null=True)),
                ('hero_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Hero description', null=True)),
                ('hero_background', models.ImageField(blank=True, help_text='Hero Background Image', null=True, upload_to='about/hero/')),
                ('button_one_text', models.CharField(blank=True, default='Explore Legacy', max_length=50, null=True)),
                ('button_one_link', models.CharField(blank=True, max_length=255, null=True)),
                ('button_two_text', models.CharField(blank=True, default='View Projects', max_length=50, null=True)),
                ('button_two_link', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text="If disabled, this section won't appear on site")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('right_image1', models.ImageField(blank=True, help_text='Main image for About section', null=True, upload_to='about/')),
                ('right_image2', models.ImageField(blank=True, help_text='Main image for About section', null=True, upload_to='about/')),
                ('years_of_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('happy_families', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'About Section',
                'ordering': ['-created_at'],
            },
        ),
    ]
