# Generated by Django 6.0.8 on 2026-08-16 17:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '2. About Section'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='about_content',
            new_name='looking_to_description',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='mission_content',
            new_name='our_mission',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='read_legacy',
            new_name='our_vision',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_subtitle',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='button_one_link',
        ),
        migrations.RemoveField(
            model_name='about',
            name='button_one_text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='button_two_link',
        ),
        migrations.RemoveField(
            model_name='about',
            name='button_two_text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='happy_families',
        ),
        migrations.RemoveField(
            model_name='about',
            name='hero_background',
        ),
        migrations.RemoveField(
            model_name='about',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='hero_highlight',
        ),
        migrations.RemoveField(
            model_name='about',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='about',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='mission_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='right_image1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='right_image2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='vision_content',
        ),
        migrations.RemoveField(
            model_name='about',
            name='vision_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='about',
            name='home_bg',
            field=models.ImageField(blank=True, help_text='Background image for home about section', null=True, upload_to='about/backgrounds/'),
        ),
        migrations.AddField(
            model_name='about',
            name='looking_to_button_link',
            field=models.URLField(blank=True, help_text='Button link (e.g., contact page)', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='looking_to_button_text',
            field=models.CharField(default='Contact Us', help_text='Call-to-action button text', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='looking_to_title',
            field=models.CharField(blank=True, help_text="Title for 'Looking To...' section", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='SEO keywords separated by commas', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='our_mission_title',
            field=models.CharField(blank=True, default='Our Mission', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='our_vision_title',
            field=models.CharField(blank=True, default='Our Vision', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='search_bg',
            field=models.ImageField(blank=True, help_text='Background image for the top search banner (optional)', null=True, upload_to='about/backgrounds/'),
        ),
        migrations.AddField(
            model_name='about',
            name='who_we_are_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Description about company identity', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='who_we_are_subtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='who_we_are_title',
            field=models.CharField(default='Who We Are', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detailed About Us content with formatting', null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(help_text="Main heading (e.g., 'About Makaan Hub')", max_length=200),
        ),
    ]
