# Generated by Django 6.0.8 on 2026-08-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_usp'),
    ]

    operations = [
        migrations.CreateModel(
            name='why_choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('icon', models.CharField(max_length=1000)),
            ],
        ),
    ]
