# Generated by Django 6.0.8 on 2026-08-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_why_choose'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='why_choose_img',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
    ]
