# Generated by Django 6.0.8 on 2026-08-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('Value', models.CharField(max_length=1000)),
                ('Suffix', models.CharField(max_length=5)),
            ],
        ),
    ]
